### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by sirdrakeistda** [SUNET/nextcloud-jupyter#1]
This project looks very interesting and I have a few questions regarding this project:
- Will this app get released in the nextcloud app store? (I would realy appreciate it)
- The code seems very specific for sunet. Is it planned to make a general functioning app for other instances or will it be easier to fork this repository?

**Comment by mickenordin** [comment]
Wow, a year later I see this issue... Sorry about that. Well the app is on the appstore: https://apps.nextcloud.com/apps/integration_jupyterhub and should be useful to anyone. certainly that is the intention.
